### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by AdamTyler** [pubnub/chat-engine-muter#3]
Attached this plugin to a chatroom and saw the error in title. Running chat-engine 0.9.10. Here is stack:
```
    at baseRest (chat-engine.js:1727)
    at nextTask (chat-engine.js:1560)
    at chat-engine.js:1564
    at apply (chat-engine.js:5510)
    at chat-engine.js:5485
    at chat-engine.js:1880
    at chat-engine.js:589
    at nextTask (chat-engine.js:1570)
    at exports.default (chat-engine.js:1573)
    at Chat.runPluginQueue (chat-engine.js:672)
```

This is seen on the browser of the person calling the mute function. Tried calling the mute on my own user and another user. Still see the same error and afterwards chat is unresponsive.

This is the code being used to test:
```
import mutePlugin from 'chat-engine-muter'
...
this.chatRoom.plugin(mutePlugin())
let ff = this.chatRoom.users['users-uuid']
this.chatRoom.muter.mute(ff)
```
`console.log(this.chatRoom.muter.isMuted(ff)) // prints true`

**Comment by AdamTyler** [comment]
@ianjennings any chance you will have time to look into this?

**Comment by ianjennings** [comment]
Hey check out 0.0.4, should fix everything.
